name: Wyam

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: |
            2.1.818
            6.0.x
      - name: Run the Cake script
        uses: cake-build/cake-action@v1
        with:
          cake-version: tool-manifest
          target: CIBuild
      - name: Deploy to GitHub Pages
        if: success() && github.event_name != 'pull_request'
        uses: Cecilapp/GitHub-Pages-deploy@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          email: ${{ secrets.MY_GITHUB_EMAIL }}
          cname: mahapps.com
          build_dir: ./output
